### ISSUE TITLE
Is there a way to turn off prompting when a new version is shipped?

### ISSUE THREAD

**Issue by jiawenzhang** [stkent/amplify#135]
I am developing an app that ships almost every week and I hope not to prompt the user that has already given feedback everytime a new version is shipped. That will be too frequent.

**Comment by stkent** [comment]
[1.1.0] Yes, you can apply custom rules when configuring your `Amplify` instance to achieve this! Here's an example that will make sure a user is _never_ prompted again after agreeing to give either positive or critical feedback:

```java
public class ExampleApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        Amplify.get(this)
               .setFeedbackEmailAddress("someone@example.com")
               .addTotalEventCountRule(PromptViewEvent.USER_GAVE_POSITIVE_FEEDBACK,
                        new MaximumCountRule(1)) // Never ask the user for feedback again if they already responded positively.
               .addTotalEventCountRule(PromptViewEvent.USER_GAVE_CRITICAL_FEEDBACK,
                        new MaximumCountRule(1)) // Never ask the user for feedback again if they already responded critically.
    }

}
```

Each rule added above can be interpreted as saying:

> Track the total number of times the event `PromptViewEvent.USER_GAVE_POSITIVE_FEEDBACK` (resp. `PromptViewEvent.USER_GAVE_CRITICAL_FEEDBACK`) occurs, and only allow the prompt to show if this count is strictly less than 1.

If that's too rigid, let me know and we can discuss your requirements in more detail :-)

**Comment by jiawenzhang** [comment]
This is exactly I wanted. Thank you! 

If I want to turn on prompt on new app release in the future, for example, after a major app release, I can just remove the rules, right?

**Comment by stkent** [comment]
There's an [issue tracking this exact feature](https://github.com/stkent/amplify/issues/106)! The plan is to allow library users to swap out the `SharedPreferences` instance in which all tracking information is stored. Then, if you want to reset all tracking for a major app update, you'll replace the `SharedPreferences` instance used in older versions of your app with a new one, and the library will 'forget' about all prior tracked events. Does that sound suitable for your needs?

Currently that issue is not assigned to a milestone, but I can bump up the priority if it's important to you, just let me know :o) Alternatively, feel free to open a PR implementing that change if you need it done quickly!

**Comment by stkent** [comment]
(If you just removed the rules, users could potentially be prompted many times in all subsequent releases).

**Comment by jiawenzhang** [comment]
I meant .applyAllDefaultRules() again after a major release, not removing all the rules. Would that re-enable prompt?

**Comment by stkent** [comment]
Unfortunately it's a little trickier than that, for a couple of reasons:

1. event tracking currently uses a single dedicated `SharedPreferences` instance (see the `com.github.stkent.amplify.tracking.Settings` class)
2. _amplify_ configuration code is run every time your application launches.

Because the library is backed by `SharedPreferences`, removing _amplify_ from one version of your app and then re-adding it in another will not reset the tracked event information - the data will still be sitting in shared preferences! For example:

- You enable _amplify_ with the default rules in v1.0.0 of your app.
- A user leaves positive feedback for v1.0.0 of your app, and this fact is recorded in shared preferences.
- The default rules prevent the user from being prompted again for v1.0.0, because we have hit the limit (1) on the number of times a user can leave positive feedback.
- You release several app updates (v1.x.x) with _amplify_ removed. No-one using these versions of the app will ever be prompted.
- You re-enable _amplify_ with the default rules in v2.0.0 of your app.
- Because shared preferences are persisted through app updates, the original user is _still_ never prompted - _amplify_ reads that saved value, and determines that we have already hit the limit (1) on the number of times a user can leave positive feedback.

It's also not possible to just add a `clear()` method to `Amplify` to wipe saved data, because the configuration code is executed every time the app starts. Data would therefore get wiped continually, and users would be prompted constantly.

This is where #106 comes in. If the library allows you to change the backing `SharedPreferences` we can effectively 'ignore' all the previously-tracked state. Then in v2.0.0, you would do something like (API specifics still TBD):

```
public class ExampleApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        Amplify.get(this)
               .setFeedbackEmailAddress("someone@example.com")
               .setSharedPreferencesName("version-2.0.0-and-later")
               .applyAllDefaultRules();
    }

}
```

You would then leave the call to `.setSharedPreferencesName("version-2.0.0-and-later")` in place until you decided to next reset all state (perhaps for v3.0.0), at which point you would replace it by `.setSharedPreferencesName("version-3.0.0-and-later")`, etc.

**Comment by jiawenzhang** [comment]
This is more complicated than I though. Thanks for the explanation.

**Comment by stkent** [comment]
You're welcome! I'll think about whether it's possible to make resetting any easier, but no alternatives spring to mind right now.

**Comment by stkent** [comment]
Per the discussion above, this can be handled as of v1.3.0 using a combination of a) only enabling prompt checks in selected app versions, and b) resetting the backing shared preferences instance when desired.
